### PR TITLE
Objects -- Remove latex, edger

### PR DESCRIPTION
**Pull request by judeallred**

### CODE REVIEW

**Comment by blubbll** [comment]
reason?

**Comment by whimsicallyson** [comment]
I agree with latex, what's unfriendly about edger? (other than the fact that I always want to type Edgar instead)

**Comment by cori** [comment]
just guessing but "edger" is one who edges, and there are sexual associations with edging.

**Comment by whimsicallyson** [comment]
that's fair! better to err on the side of caution anyhow :)

**Comment by judeallred** [comment]
Thanks :-)  I'll be better about stating my reasons in future PR's.
This this case, both words were reported to me verbally in a "well, this is awkard..." context,  and I'm following on the 'err on the side of child friendliness when there are ambiguities' guidelines.

**Pull request merged**
